spring: 
   profiles:
      active: prod

---    
spring:
   config:
      active:
         on-profile: dev
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      properties:
         hibernate:
            format-sql: true
            dialect: org.hibernate.dialect.PostgreSQLDialect            
   datasource:
      url: jdbc:postgresql://localhost:5432/test
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}      
   application:
      name: keycloak-demo
   security:
      oauth2:
         resourceserver:
            jwt:
               issuer-uri: http://localhost:8180/realms/keycloak-demo
               jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
         client:
            registration:
               google:
                  client-id: ${GOOGLE_CLIENT_ID}
                  client-secret: ${GOOGLE_CLIENT_SECRET}
                  redirect-uri: http://localhost:8080/api/auth/token-exchange
jwt:
   auth:
      converter:
         resource-id: ${KEYCLOAK_CLIENT_ID}
         principal-attribute: preferred_username
        
logging:
  level:
    org.springframework.security: DEBUG